[toolchain]
anchor_version = "0.31.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
keeper_book = "BhstTkGhG1LLPYBt3E3n4PTZ3v1V6ukNHYvQ88rgvTHS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
